// <auto-generated />
using BCT.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BCT.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250623092419_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("BCT.Domain.Entities.BoolValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BoolValue");
                });

            modelBuilder.Entity("BCT.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BtwNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BCT.Domain.Entities.DoubleValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<int?>("Year")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DoubleValues");
                });

            modelBuilder.Entity("BCT.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChosenGridMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Horizon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InterestEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BCT.Domain.Entities.ProjectGridWizard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvoidedCostEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvoidedInvestment")
                        .HasColumnType("REAL");

                    b.Property<string>("AvoidedInvestmentDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AvoidedInvestmentEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvoidedInvestmentYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("EnergyDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EnergyOvoided")
                        .HasColumnType("REAL");

                    b.Property<string>("EnergyOvoidedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnergyOvoidedYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnergyYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Equipment")
                        .HasColumnType("REAL");

                    b.Property<string>("EquipmentDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EquipmentOvoided")
                        .HasColumnType("REAL");

                    b.Property<string>("EquipmentOvoidedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentOvoidedYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EquipmentUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("EquipmentUsageDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EquipmentUsageOvoided")
                        .HasColumnType("REAL");

                    b.Property<string>("EquipmentUsageOvoidedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentUsageOvoidedYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentUsageYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ExtraIncome")
                        .HasColumnType("REAL");

                    b.Property<string>("ExtraIncomeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExtraIncomeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraIncomeYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Horizon")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ICTHardware")
                        .HasColumnType("REAL");

                    b.Property<string>("ICTHardwareDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ICTHardwareYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ICTSoftware")
                        .HasColumnType("REAL");

                    b.Property<string>("ICTSoftwareDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ICTSoftwareYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Interest")
                        .HasColumnType("REAL");

                    b.Property<bool>("InterestEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LostIncome")
                        .HasColumnType("REAL");

                    b.Property<string>("LostIncomeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LostIncomeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LostIncomeYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NewInvestment")
                        .HasColumnType("REAL");

                    b.Property<string>("NewInvestmentDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NewInvestmentYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Other")
                        .HasColumnType("REAL");

                    b.Property<string>("OtherDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OtherOvoided")
                        .HasColumnType("REAL");

                    b.Property<string>("OtherOvoidedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OtherOvoidedYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OtherYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Personnel")
                        .HasColumnType("REAL");

                    b.Property<string>("PersonnelDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PersonnelOvoided")
                        .HasColumnType("REAL");

                    b.Property<string>("PersonnelOvoidedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelOvoidedYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonnelYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ResidualValue")
                        .HasColumnType("REAL");

                    b.Property<string>("ResidualValueDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ResidualValueEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProjectGridWizards");
                });

            modelBuilder.Entity("BCT.Domain.Entities.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvoidedCostDif")
                        .HasColumnType("REAL");

                    b.Property<double>("AvoidedCostMod")
                        .HasColumnType("REAL");

                    b.Property<double>("AvoidedInvestmentDif")
                        .HasColumnType("REAL");

                    b.Property<double>("AvoidedInvestmentMod")
                        .HasColumnType("REAL");

                    b.Property<double>("CostDif")
                        .HasColumnType("REAL");

                    b.Property<double>("CostMod")
                        .HasColumnType("REAL");

                    b.Property<double>("IncomeDif")
                        .HasColumnType("REAL");

                    b.Property<double>("IncomeMod")
                        .HasColumnType("REAL");

                    b.Property<double>("InvestmentDif")
                        .HasColumnType("REAL");

                    b.Property<double>("InvestmentMod")
                        .HasColumnType("REAL");

                    b.Property<double>("LostIncomeDif")
                        .HasColumnType("REAL");

                    b.Property<double>("LostIncomeMod")
                        .HasColumnType("REAL");

                    b.Property<byte>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SensitivityScenarios");
                });

            modelBuilder.Entity("BCT.Domain.Entities.StringValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StringValue");
                });

            modelBuilder.Entity("BCT.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Text")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BCT.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("LastCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CompanyUser", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompanyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUser");
                });

            modelBuilder.Entity("ProjectTag", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProjectTag");
                });

            modelBuilder.Entity("BCT.Domain.Entities.Company", b =>
                {
                    b.HasOne("BCT.Domain.Entities.User", "Creator")
                        .WithMany("CreatedCompanies")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BCT.Domain.Entities.Project", b =>
                {
                    b.HasOne("BCT.Domain.Entities.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BCT.Domain.Entities.Tag", b =>
                {
                    b.HasOne("BCT.Domain.Entities.Company", "Company")
                        .WithMany("Tags")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyUser", b =>
                {
                    b.HasOne("BCT.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BCT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTag", b =>
                {
                    b.HasOne("BCT.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BCT.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BCT.Domain.Entities.Company", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BCT.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
