<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BCT.Application\BCT.Application.csproj" />
    <ProjectReference Include="..\BCT.Logging\BCT.Logging.csproj" />
  </ItemGroup>

</Project>
