<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Components\" />
    <Folder Include="wwwroot\js\" />
    <Folder Include="wwwroot\harveyballs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Auth0.AspNetCore.Authentication" Version="1.4.1" />
    <PackageReference Include="Blazor-ApexCharts" Version="5.1.0" />
    <PackageReference Include="Microsoft.Playwright" Version="1.52.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.SQLite" Version="6.0.0" />
    <PackageReference Include="Sqids" Version="3.1.0" />
    <PackageReference Include="BlazorAnimate" Version="3.0.0" />
    <PackageReference Include="BlazorIntersectionObserver" Version="3.1.0" />
    <PackageReference Include="Radzen.Blazor" Version="5.6.15" />
    <PackageReference Include="ThrottleDebounce" Version="2.0.1" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BCT.Domain\BCT.Domain.csproj" />
    <ProjectReference Include="..\BCT.Infrastructure\BCT.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\favicon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\logo.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
